# Generated by Django 5.0.6 on 2026-04-05 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(default=2024)),
                ('toe_calculated', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('data_source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('API', 'API'), ('EXCEL', 'Excel Upload')], default='MANUAL', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('industry_category', models.CharField(blank=True, max_length=100)),
                ('consumption_type', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('FUEL', 'Fuel'), ('COAL', 'Coal'), ('OTHER', 'Other')], max_length=20)),
                ('energy_consumption', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=20)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.industryclassification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'industry_consumption',
            },
        ),
    ]
