# Generated by Django 5.0.6 on 2026-04-18 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
        ('master_data', '0002_rename_operator_generationplant_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryconsumption',
            name='consumption_type',
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.fueltype'),
        ),
        migrations.AlterField(
            model_name='industryconsumption',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.measurementunit'),
        ),
    ]
