# Generated by Django 5.0.6 on 2026-04-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0002_remove_industryconsumption_consumption_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryconsumption',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
