# Generated by Django 5.0.6 on 2026-06-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0004_alter_industryconsumption_data_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industryconsumption',
            options={'ordering': ['-date', 'industry_category']},
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='date',
            field=models.DateField(blank=True, db_column='date', null=True),
        ),
    ]
