# Generated by Django 5.0.6 on 2026-06-21 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0005_alter_industryconsumption_options_and_more'),
        ('master_data', '0012_circuittype_conductortype_configurationtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industryconsumption',
            options={'ordering': ['-date', 'name_industry']},
        ),
        migrations.RemoveField(
            model_name='industryconsumption',
            name='energy_consumption',
        ),
        migrations.RemoveField(
            model_name='industryconsumption',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='industryconsumption',
            name='industry_category',
        ),
        migrations.RemoveField(
            model_name='industryconsumption',
            name='unit',
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='bamboo_mt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='briquettes_mt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='charcoal_mt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='coal_mt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='coke_lamc_mt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='diesel_lt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='dolomite_mt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='electricity_kWh',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='furnace_oil_lt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='kerosene_lt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='limestone_mt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='lubricants_lt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='name_industry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='sawdust_mt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='semicoke_mt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='type_industry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='industryconsumption',
            name='woodchips_mt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='industryconsumption',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.industryclassification'),
        ),
    ]
