# Generated by Django 5.0.6 on 2026-04-18 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coal', '0002_alter_coaldata_category_alter_coaldata_unit'),
        ('master_data', '0002_rename_operator_generationplant_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaldata',
            name='dzongkhag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.dzongkhag'),
        ),
        migrations.AddField(
            model_name='coaldata',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.sector'),
        ),
    ]
