# Generated by Django 5.0.6 on 2026-04-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coal', '0003_coaldata_dzongkhag_coaldata_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaldata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
