# Generated by Django 5.0.6 on 2026-06-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coal', '0005_alter_coaldata_data_source_alter_coaldata_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaldata',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coaldata',
            name='dzongkhag',
        ),
        migrations.RemoveField(
            model_name='coaldata',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='coaldata',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='coaldata',
            name='unit',
        ),
        migrations.AddField(
            model_name='coaldata',
            name='coal_type',
            field=models.CharField(blank=True, db_column='coal_type', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coaldata',
            name='date',
            field=models.DateField(blank=True, db_column='date', null=True),
        ),
        migrations.AddField(
            model_name='coaldata',
            name='destination',
            field=models.CharField(blank=True, db_column='destination', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coaldata',
            name='mineral_type',
            field=models.CharField(blank=True, db_column='mineral_type', default='Coal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coaldata',
            name='quantity_mt',
            field=models.DecimalField(blank=True, db_column='quantity_mt', decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='coaldata',
            name='source',
            field=models.CharField(blank=True, db_column='source', max_length=255, null=True),
        ),
    ]
