# Generated by Django 5.0.6 on 2026-06-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coal', '0006_remove_coaldata_category_remove_coaldata_dzongkhag_and_more'),
        ('master_data', '0010_generationplant_plant_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaldata',
            name='coal_type',
            field=models.ForeignKey(blank=True, db_column='coal_type', null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.fueltype'),
        ),
    ]
