# Generated by Django 5.0.6 on 2026-03-03 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('toe_calculated', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('data_source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('API', 'API'), ('EXCEL', 'Excel Upload')], default='MANUAL', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('dzongkhag', models.CharField(choices=[('bumthang', 'Bumthang'), ('chhukha', 'Chhukha'), ('dagana', 'Dagana'), ('gasa', 'Gasa'), ('haa', 'Haa'), ('lhuentse', 'Lhuentse'), ('mongar', 'Mongar'), ('paro', 'Paro'), ('pemagatshel', 'Pemagatshel'), ('punakha', 'Punakha'), ('samdrup_jongkhar', 'Samdrup Jongkhar'), ('samtse', 'Samtse'), ('sarpang', 'Sarpang'), ('thimphu', 'Thimphu'), ('trashigang', 'Trashigang'), ('trashiyangtse', 'Trashiyangtse'), ('trongsa', 'Trongsa'), ('tsirang', 'Tsirang'), ('wangdue_phodrang', 'Wangdue Phodrang'), ('zhemgang', 'Zhemgang')], max_length=50)),
                ('demand_mwh', models.DecimalField(decimal_places=4, max_digits=18)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumption_records', to='master_data.electricitycategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electricity_consumption', to='master_data.sector')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'electricity_consumption',
            },
        ),
        migrations.CreateModel(
            name='ElectricityGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('toe_calculated', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('data_source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('API', 'API'), ('EXCEL', 'Excel Upload')], default='MANUAL', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('supply_source', models.CharField(choices=[('HYDRO', 'Hydro'), ('SOLAR', 'Solar'), ('WIND', 'Wind'), ('THERMAL', 'Thermal')], max_length=20)),
                ('quantity_mwh', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'electricity_generation',
            },
        ),
        migrations.CreateModel(
            name='ElectricityImportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('toe_calculated', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('data_source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('API', 'API'), ('EXCEL', 'Excel Upload')], default='MANUAL', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('transaction_type', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export')], max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('quantity_mwh', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'electricity_import_export',
            },
        ),
    ]
