# Generated by Django 5.0.6 on 2026-03-03 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('ELECTRICITY', 'Electricity Balance'), ('SOLAR', 'Solar Installations & Output'), ('FUELWOOD', 'Fuelwood Supply & Demand'), ('POL', 'POL Trade & Use'), ('TRANSPORT', 'Road Transport Fuel Consumption'), ('BIOGAS', 'Biogas Plant Inventory'), ('BRIQUETTE', 'Briquette / Charcoal'), ('COAL', 'Coal Production & Flows'), ('INDUSTRY', 'Industrial Energy Use')], max_length=20)),
                ('filters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reporting_request',
            },
        ),
    ]
