# Generated by Django 5.0.6 on 2026-04-05 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POLAviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(default=2024)),
                ('toe_calculated', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('data_source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('API', 'API'), ('EXCEL', 'Excel Upload')], default='MANUAL', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('quantity_kl', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(default='KL', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aviation_consumption', to='master_data.sector')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pol_aviation',
            },
        ),
        migrations.CreateModel(
            name='POLImportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(default=2024)),
                ('toe_calculated', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('data_source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('API', 'API'), ('EXCEL', 'Excel Upload')], default='MANUAL', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('transaction_type', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export')], max_length=10)),
                ('main_category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('quantity_kl', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(default='KL', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pol_import_export',
            },
        ),
        migrations.CreateModel(
            name='TransportConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(default=2024)),
                ('toe_calculated', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('data_source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('API', 'API'), ('EXCEL', 'Excel Upload')], default='MANUAL', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('OTHER', 'Other')], max_length=20)),
                ('odometer_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fuel_consumed_calculated', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('original_vehicle_type', models.CharField(blank=True, max_length=100)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.vehicletype')),
            ],
            options={
                'db_table': 'pol_transport_consumption',
            },
        ),
    ]
