# Generated by Django 5.0.6 on 2026-04-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_rename_operator_generationplant_owner_and_more'),
        ('pol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polaviation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.measurementunit'),
        ),
        migrations.AlterField(
            model_name='polimportexport',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pol_imports', to='master_data.fueltype'),
        ),
        migrations.AlterField(
            model_name='polimportexport',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pol_sub_imports', to='master_data.fueltype'),
        ),
        migrations.AlterField(
            model_name='polimportexport',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.measurementunit'),
        ),
        migrations.AlterField(
            model_name='transportconsumption',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.vehiclefueltype'),
        ),
    ]
