# Generated by Django 5.0.6 on 2026-04-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pol', '0002_alter_polaviation_unit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransportConsumption',
        ),
    ]
