# Generated by Django 5.0.6 on 2026-04-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol', '0003_delete_transportconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='polaviation',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
