# Generated by Django 5.0.6 on 2026-06-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol', '0005_alter_polaviation_data_source_alter_polaviation_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polimportexport',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='polimportexport',
            name='quantity_kl',
        ),
        migrations.RemoveField(
            model_name='polimportexport',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='polimportexport',
            name='unit',
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='btc_chapter',
            field=models.CharField(blank=True, db_column='btc_chapter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='btc_code',
            field=models.CharField(blank=True, db_column='btc_code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='country_of_exportation',
            field=models.CharField(blank=True, db_column='country_of_exportation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='country_of_origin',
            field=models.CharField(blank=True, db_column='country_of_origin', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='customs_office',
            field=models.CharField(blank=True, db_column='customs_office', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='customs_value_nu',
            field=models.DecimalField(blank=True, db_column='customs_value_nu', decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='declaration_date',
            field=models.DateTimeField(blank=True, db_column='declaration_date', null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='declaration_number',
            field=models.CharField(blank=True, db_column='declaration_number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='exporter_name',
            field=models.CharField(blank=True, db_column='exporter_name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='full_description',
            field=models.TextField(blank=True, db_column='full_description', null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='importer_name',
            field=models.CharField(blank=True, db_column='importer_name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='importer_tpn',
            field=models.CharField(blank=True, db_column='importer_tpn', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='invoice_date',
            field=models.DateField(blank=True, db_column='invoice_date', null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='invoice_number',
            field=models.CharField(blank=True, db_column='invoice_number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='quantity',
            field=models.DecimalField(blank=True, db_column='quantity', decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='rrco_office',
            field=models.CharField(blank=True, db_column='rrco_office', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='standard_unit_id',
            field=models.CharField(blank=True, db_column='standard_unit_id', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='polimportexport',
            name='vehicle_number',
            field=models.CharField(blank=True, db_column='vehicle_number', max_length=100, null=True),
        ),
    ]
