# Generated by Django 5.0.6 on 2026-06-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol', '0006_remove_polimportexport_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polimportexport',
            name='customs_value_nu',
            field=models.DecimalField(blank=True, db_column='customs_value_nu', decimal_places=6, max_digits=18, null=True),
        ),
    ]
