# Generated by Django 5.0.6 on 2026-04-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_transport', '0002_transportconsumption_vehicleregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportconsumption',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
