# Generated by Django 5.0.6 on 2026-04-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_rename_operator_generationplant_owner_and_more'),
        ('surface_transport', '0003_transportconsumption_day_vehicleregistration_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transportconsumption',
            unique_together={('year', 'month', 'day', 'vehicle_type', 'fuel_type')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicleregistration',
            unique_together={('year', 'month', 'day', 'dzongkhag', 'vehicle_type', 'fuel_type')},
        ),
    ]
