# Generated by Django 5.0.6 on 2026-05-21 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_add_vehicletype_parent_field'),
        ('surface_transport', '0005_alter_transportconsumption_data_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleregistration',
            options={'ordering': ['-initial_registration_date'], 'verbose_name': 'Vehicle Registration', 'verbose_name_plural': 'Vehicle Registrations'},
        ),
        migrations.AlterUniqueTogether(
            name='vehicleregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='engine_cc',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Engine displacement in cubic centimetres (cc)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='gross_vehicle_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross vehicle weight in kilograms (kg)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='horse_power',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Engine power in horsepower (HP)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='initial_registration_date',
            field=models.DateField(blank=True, help_text='Date the vehicle was first registered', null=True),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='kilo_watt_hour',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Battery capacity in kWh (for EVs)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='model_name',
            field=models.CharField(blank=True, help_text='Make and model of the vehicle (e.g. Toyota Hilux)', max_length=200),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='seating_capacity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of seats (passengers)', null=True),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SCRAPPED', 'Scrapped'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='fuel_type',
            field=models.ForeignKey(help_text='Primary fuel or energy source', on_delete=django.db.models.deletion.PROTECT, related_name='vehicleregistration', to='master_data.vehiclefueltype'),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='vehicle_type',
            field=models.ForeignKey(help_text='Type / category of the vehicle', on_delete=django.db.models.deletion.PROTECT, related_name='vehicleregistration', to='master_data.vehicletype'),
        ),
        migrations.AlterModelTable(
            name='vehicleregistration',
            table='transport_vehicle_registration',
        ),
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='count',
        ),
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='day',
        ),
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='dzongkhag',
        ),
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='month',
        ),
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='toe_calculated',
        ),
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='year',
        ),
    ]
