# Generated by Django 5.0.6 on 2026-05-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_transport', '0006_update_vehicle_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregistration',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('OUTSTANDING', 'Outstanding')], default='ACTIVE', max_length=20),
        ),
    ]
