# Generated by Django 5.0.6 on 2026-05-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_transport', '0007_alter_vehicleregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregistration',
            name='registration_no',
            field=models.CharField(help_text='Unique Registration Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='initial_registration_date',
            field=models.DateField(default='2024-01-01', help_text='Date the vehicle was first registered'),
            preserve_default=False,
        ),
    ]
