# Generated by Django 5.0.6 on 2026-05-21 14:43

import uuid
from django.db import migrations

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('surface_transport', 'VehicleRegistration')
    for row in MyModel.objects.all():
        row.registration_no = uuid.uuid4()
        row.save(update_fields=['registration_no'])


class Migration(migrations.Migration):

    dependencies = [
        ('surface_transport', '0008_vehicleregistration_registration_no_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
