# Generated by Django 5.0.6 on 2026-05-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_transport', '0009_populate_registration_no_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregistration',
            name='registration_no',
            field=models.CharField(help_text='Unique Registration Number', max_length=100, unique=True),
        ),
    ]
