# Generated by Django 5.0.6 on 2026-05-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_transport', '0010_alter_vehicleregistration_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregistration',
            name='owner_type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Organization', 'Organization')], help_text='Type of owner (Individual or Organization)', max_length=20, null=True),
        ),
    ]
