# Generated by Django 5.0.6 on 2026-05-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_transport', '0011_vehicleregistration_owner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregistration',
            name='model_name',
            field=models.CharField(blank=True, help_text='Make and model of the vehicle (e.g. Toyota Hilux)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('OUTSTANDING', 'Outstanding')], default='ACTIVE', max_length=20, null=True),
        ),
    ]
