# Generated by Django 5.0.6 on 2026-06-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surface_transport', '0012_alter_vehicleregistration_model_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transportconsumption',
            table='surface_transport_consumption',
        ),
        migrations.AlterModelTable(
            name='vehicleregistration',
            table='surface_transport_vehicle_registration',
        ),
    ]
