# Generated by Django 5.0.6 on 2026-03-03 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('toe_calculated', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('data_source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('API', 'API'), ('EXCEL', 'Excel Upload')], default='MANUAL', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('PRODUCTION', 'Production'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('CONSUMPTION', 'Consumption')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coal_data',
            },
        ),
    ]
