# Generated by Django 5.0.6 on 2026-05-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_bulkimportjob_bulkimporterror'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkimportjob',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='import_jobs/'),
        ),
        migrations.AlterField(
            model_name='bulkimportjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
