# Generated by Django 5.0.6 on 2026-05-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_bulkexportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkexportjob',
            name='processed_rows',
            field=models.IntegerField(default=0),
        ),
    ]
