# Generated by Django 5.0.6 on 2026-06-17 19:45

import eis_apps.administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_bulkexportjob_processed_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('tagline', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='landing_slides/')),
                ('cta_text', models.CharField(blank=True, default='Live Dashboard', max_length=50)),
                ('cta_link', models.CharField(blank=True, default='/public', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'landing_page_slides',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='landing_body_integrations',
            field=models.JSONField(blank=True, default=eis_apps.administration.models.default_landing_body_integrations),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='landing_body_sectors',
            field=models.JSONField(blank=True, default=eis_apps.administration.models.default_landing_body_sectors),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='landing_footer',
            field=models.JSONField(blank=True, default=eis_apps.administration.models.default_landing_footer),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='landing_header',
            field=models.JSONField(blank=True, default=eis_apps.administration.models.default_landing_header),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_auth_url',
            field=models.URLField(blank=True, default='https://staging.bhutanndi.com/authentication/v1/authenticate', help_text='POST - get OAuth2 Bearer token using client_id + client_secret. Swagger: https://staging.bhutanndi.com/authentication/swagger', verbose_name='NDI Auth URL (Staging)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_issuer_url',
            field=models.URLField(blank=True, default='https://demo-client.bhutanndi.com/issuer/v1', help_text='POST - issue/revoke verifiable credentials. Swagger: https://demo-client.bhutanndi.com/issuer/swagger', verbose_name='NDI Issuer URL (Staging)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_nats_seed',
            field=models.CharField(blank=True, help_text='Dev seed (not secret in staging): SUAPXY7TJFUFE3IX3OEMSLE3JFZJ3FZZRSRSOGSG2ANDIFN77O2MIBHWUM - treat production seed as secret', max_length=500, verbose_name='NDI NATS Seed (Dev)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_nats_ws_url',
            field=models.CharField(blank=True, default='wss://natsdemoclient.bhutanndi.com', help_text='WebSocket URL - wss:// protocol not validated as URL', max_length=500, verbose_name='NDI NATS WebSocket URL'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_schema_id',
            field=models.URLField(blank=True, default='https://dev-schema.ngotag.com/schemas/c7952a0a-e9b5-4a4b-a714-1e5d0a1ae076', help_text='Schema URL for requesting ID Number and Full Name from Foundational ID credential', verbose_name='NDI Schema ID - Foundational ID'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_verifier_url',
            field=models.URLField(blank=True, default='https://demo-client.bhutanndi.com/verifier/v1/proof-request', help_text='POST - create proof request. GET - poll proof status. Swagger: https://demo-client.bhutanndi.com/verifier/swagger', verbose_name='NDI Verifier URL (Staging)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_webhook_secret',
            field=models.CharField(blank=True, help_text='OAuth2 v2 fixed token - NDI sends this in Authorization header to authenticate webhook calls to our server', max_length=255, verbose_name='NDI Webhook Secret'),
        ),
    ]
