# Generated by Django 5.0.6 on 2026-06-17

from django.db import migrations

def seed_slides(apps, schema_editor):
    LandingPageSlide = apps.get_model('administration', 'LandingPageSlide')
    LandingPageSlide.objects.get_or_create(
        id=1,
        defaults={
            "title": "National Energy Information System",
            "tagline": "Bhutan's unified platform for energy data management, consumption monitoring, and national statistics.",
            "image": "landing_slides/hero1.jpg",
            "cta_text": "Live Dashboard",
            "cta_link": "/public",
            "order": 0,
        }
    )
    LandingPageSlide.objects.get_or_create(
        id=2,
        defaults={
            "title": "Sustainable Energy Transition",
            "tagline": "Tracking renewable energy capacity, solar integration, and biomass consumption nationwide.",
            "image": "landing_slides/hero2.jpg",
            "cta_text": "Live Dashboard",
            "cta_link": "/public",
            "order": 1,
        }
    )
    LandingPageSlide.objects.get_or_create(
        id=3,
        defaults={
            "title": "Dynamic Flow Modeling",
            "tagline": "Sankey diagrams, regional energy balances, and interactive dzongkhag-level consumption trends.",
            "image": "landing_slides/hero3.jpg",
            "cta_text": "Live Dashboard",
            "cta_link": "/public",
            "order": 2,
        }
    )

def remove_slides(apps, schema_editor):
    LandingPageSlide = apps.get_model('administration', 'LandingPageSlide')
    LandingPageSlide.objects.filter(id__in=[1, 2, 3]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_landingpageslide_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_slides, remove_slides),
    ]
