# Generated by Django 5.0.6 on 2026-06-17 19:54

import eis_apps.administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_seed_landing_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='landing_faqs',
            field=models.JSONField(blank=True, default=eis_apps.administration.models.default_landing_faqs),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='landing_page_settings',
            field=models.JSONField(blank=True, default=eis_apps.administration.models.default_landing_page_settings),
        ),
    ]
