# Generated by Django 5.0.6 on 2026-06-18

from django.db import migrations

def seed_site_setting(apps, schema_editor):
    SiteSetting = apps.get_model('administration', 'SiteSetting')
    
    # We retrieve the default JSON field structures
    from eis_apps.administration.models import (
        default_landing_header,
        default_landing_body_sectors,
        default_landing_body_integrations,
        default_landing_footer,
        default_landing_faqs,
        default_landing_page_settings
    )
    
    obj, created = SiteSetting.objects.get_or_create(pk=1)
    
    obj.site_title = "Energy Information System"
    obj.site_short_name = "EIS"
    obj.site_tagline = "Department of Energy · MoENR · Royal Government of Bhutan"
    obj.contact_email = "support@energy.gov.bt"
    obj.contact_address = "Department of Energy, MoENR, Thimphu, Bhutan"
    obj.website_url = "https://www.moea.gov.bt"
    obj.allow_ndi_login = True
    obj.allow_agency_login = True
    obj.maintenance_mode = False
    obj.footer_text = "© 2026 Department of Energy, MoENR, Royal Government of Bhutan. All rights reserved."
    obj.copyright_year = "2026"
    
    obj.landing_header = default_landing_header()
    obj.landing_body_sectors = default_landing_body_sectors()
    obj.landing_body_integrations = default_landing_body_integrations()
    obj.landing_footer = default_landing_footer()
    obj.landing_faqs = default_landing_faqs()
    obj.landing_page_settings = default_landing_page_settings()
    
    obj.save()

def rollback_site_setting(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_sitesetting_landing_faqs_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_site_setting, rollback_site_setting),
    ]
