# Generated by Django 5.0.6 on 2026-06-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_seed_site_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=50)),
            ],
            options={
                'db_table': 'block_types',
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageSection',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=20)),
                ('desc', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'landing_page_sections',
                'ordering': ['order', 'id'],
            },
        ),
    ]
