# Generated by Django 5.0.6 on 2026-06-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetlibrary',
            name='chart_type',
            field=models.CharField(choices=[('STAT', 'Single Statistic'), ('BAR', 'Bar Chart'), ('PIE', 'Pie Chart'), ('LINE', 'Line Chart'), ('AREA', 'Area Chart'), ('RADAR', 'Radar Chart'), ('MAP', 'Choropleth Map'), ('SANKEY', 'Sankey Diagram'), ('TABLE', 'Data Table')], max_length=10),
        ),
    ]
