# Generated by Django 5.0.6 on 2026-04-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_rename_operator_generationplant_owner_and_more'),
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarenergy',
            name='dzongkhag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.dzongkhag'),
        ),
        migrations.AlterField(
            model_name='solarenergy',
            name='solar_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.electricitytype'),
        ),
    ]
