# Generated by Django 5.0.6 on 2026-03-19 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_email_otp_user_email_verified_user_mfa_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('bar_chart', 'Bar Chart'), ('line_chart', 'Line Chart'), ('pie_chart', 'Pie Chart'), ('area_chart', 'Area Chart'), ('stat_card', 'Stat Card'), ('data_table', 'Data Table'), ('map_view', 'Map View')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('data_module', models.CharField(blank=True, max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=6)),
                ('height', models.IntegerField(default=4)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_dashboard_widget',
                'ordering': ['user', 'position_y', 'position_x'],
            },
        ),
    ]
