# Generated by Django 5.0.6 on 2026-04-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelwood', '0001_initial'),
        ('master_data', '0002_rename_operator_generationplant_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelwoodconsumption',
            name='dzongkhag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.dzongkhag'),
        ),
        migrations.AlterField(
            model_name='fuelwoodconsumption',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.fueltype'),
        ),
        migrations.AlterField(
            model_name='fuelwoodsupply',
            name='dzongkhag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.dzongkhag'),
        ),
        migrations.AlterField(
            model_name='fuelwoodsupply',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.fueltype'),
        ),
    ]
