# Generated by Django 5.0.6 on 2026-04-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelwood', '0002_alter_fuelwoodconsumption_dzongkhag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelwoodconsumption',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelwoodsupply',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
