# Generated by Django 5.0.6 on 2026-06-05 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelwood', '0004_alter_fuelwoodconsumption_data_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelwoodconsumption',
            options={'ordering': ['-permit_date', 'office'], 'verbose_name': 'Fuelwood Consumption Record', 'verbose_name_plural': 'Fuelwood Consumption Records'},
        ),
        migrations.AlterModelOptions(
            name='fuelwoodsupply',
            options={'ordering': ['-permit_date', 'office'], 'verbose_name': 'Fuelwood Supply Record', 'verbose_name_plural': 'Fuelwood Supply Records'},
        ),
        migrations.RemoveField(
            model_name='fuelwoodconsumption',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='fuelwoodconsumption',
            name='quantity_tonnes',
        ),
        migrations.RemoveField(
            model_name='fuelwoodconsumption',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='fuelwoodsupply',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='fuelwoodsupply',
            name='quantity_tonnes',
        ),
        migrations.AddField(
            model_name='fuelwoodconsumption',
            name='office',
            field=models.CharField(default='', help_text='Office Name', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelwoodconsumption',
            name='permit_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Permit Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelwoodconsumption',
            name='purpose',
            field=models.CharField(blank=True, help_text='Purpose', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fuelwoodconsumption',
            name='purpose_group',
            field=models.CharField(blank=True, help_text='Purpose Group', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fuelwoodconsumption',
            name='quantity_m3',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Quantity in Metre Cube (m3)', max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelwoodsupply',
            name='office',
            field=models.CharField(default='', help_text='Office Name', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelwoodsupply',
            name='permit_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Permit Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelwoodsupply',
            name='purpose',
            field=models.CharField(blank=True, help_text='Purpose', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fuelwoodsupply',
            name='quantity_m3',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Quantity in Metre Cube (m3)', max_digits=18),
            preserve_default=False,
        ),
    ]
