# Generated by Django 5.0.6 on 2026-05-01 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomass', '0003_biogasdata_day_briquettecharcoal_day'),
        ('master_data', '0002_rename_operator_generationplant_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biogasdata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='biogasdata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='briquettecharcoal',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='briquettecharcoal',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
    ]
