# Generated by Django 5.0.6 on 2026-06-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomass', '0004_alter_biogasdata_data_source_alter_biogasdata_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasdata',
            name='date',
            field=models.DateField(blank=True, db_column='date', null=True),
        ),
        migrations.AddField(
            model_name='briquettecharcoal',
            name='date',
            field=models.DateField(blank=True, db_column='date', null=True),
        ),
    ]
