# Generated by Django 5.0.6 on 2026-03-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Energy Information System', max_length=200)),
                ('site_short_name', models.CharField(default='EIS', max_length=50)),
                ('site_tagline', models.CharField(blank=True, default='Department of Energy · MoENR · Royal Government of Bhutan', max_length=300)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('doe_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('gov_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(blank=True, default='support@energy.gov.bt', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_address', models.TextField(blank=True, default='Department of Energy, MoENR, Thimphu, Bhutan')),
                ('website_url', models.URLField(blank=True, default='https://www.moea.gov.bt')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_msg', models.TextField(blank=True, default='The system is under maintenance. Please try again later.')),
                ('allow_ndi_login', models.BooleanField(default=True)),
                ('allow_agency_login', models.BooleanField(default=True)),
                ('session_timeout', models.PositiveIntegerField(default=480, help_text='Session timeout in minutes')),
                ('max_login_attempts', models.PositiveSmallIntegerField(default=5)),
                ('footer_text', models.TextField(blank=True, default='© 2026 Department of Energy, MoENR, Royal Government of Bhutan. All rights reserved.')),
                ('copyright_year', models.CharField(default='2026', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'db_table': 'site_settings',
            },
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dataimporthistory',
            name='imported_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='APILog',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='DataImportHistory',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='SystemConfig',
        ),
    ]
