# Generated by Django 5.0.6 on 2026-03-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_sitesetting_remove_auditlog_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndi_client_id', models.CharField(blank=True, max_length=255, verbose_name='NDI Client ID')),
                ('ndi_client_secret', models.CharField(blank=True, help_text='Stored securely. Leave blank to keep existing value.', max_length=255, verbose_name='NDI Client Secret')),
                ('ndi_webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='NDI Webhook Secret')),
                ('ndi_webhook_id', models.CharField(blank=True, default='eis-bhutan-26', max_length=100, verbose_name='NDI Webhook ID')),
                ('ndi_webhook_base_url', models.URLField(blank=True, default='https://your-ngrok-url.ngrok-free.dev', help_text='Public URL Django is reachable at. Re-run register_ndi_webhook after changing.', verbose_name='Webhook Base URL (ngrok/domain)')),
                ('ndi_auth_url', models.URLField(blank=True, default='https://staging.bhutanndi.com/authentication/v1/authenticate', verbose_name='NDI Auth URL')),
                ('ndi_verifier_url', models.URLField(blank=True, default='https://demo-client.bhutanndi.com/verifier/v1/proof-request', verbose_name='NDI Verifier URL')),
                ('ndi_schema_id', models.URLField(blank=True, default='https://dev-schema.ngotag.com/schemas/c7952a0a-e9b5-4a4b-a714-1e5d0a1ae076', verbose_name='NDI Schema ID (Foundational ID)')),
                ('ndi_environment', models.CharField(choices=[('staging', 'Staging / Dev'), ('production', 'Production')], default='staging', max_length=20, verbose_name='NDI Environment')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text="Use 'django.core.mail.backends.console.EmailBackend' for dev/testing", max_length=200, verbose_name='Email Backend')),
                ('email_host', models.CharField(blank=True, help_text='e.g. smtp.gmail.com or smtp.gov.bt', max_length=255, verbose_name='SMTP Host')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='SMTP Port')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Use SSL instead of TLS (port 465)', verbose_name='Use SSL')),
                ('email_host_user', models.CharField(blank=True, max_length=255, verbose_name='SMTP Username / Email')),
                ('email_host_password', models.CharField(blank=True, help_text='Leave blank to keep existing value.', max_length=255, verbose_name='SMTP Password')),
                ('default_from_email', models.EmailField(blank=True, default='noreply@doe.gov.bt', max_length=254, verbose_name='Default From Email')),
                ('email_timeout', models.PositiveIntegerField(default=30, verbose_name='SMTP Timeout (seconds)')),
                ('api_1_name', models.CharField(blank=True, help_text='e.g. GovTech Data API', max_length=100, verbose_name='API 1 — Name')),
                ('api_1_key', models.CharField(blank=True, max_length=500, verbose_name='API 1 — Key / Token')),
                ('api_1_base_url', models.URLField(blank=True, verbose_name='API 1 — Base URL')),
                ('api_1_enabled', models.BooleanField(default=False, verbose_name='API 1 — Enabled')),
                ('api_2_name', models.CharField(blank=True, help_text='e.g. Bhutan Telecom SMS Gateway', max_length=100, verbose_name='API 2 — Name')),
                ('api_2_key', models.CharField(blank=True, max_length=500, verbose_name='API 2 — Key / Token')),
                ('api_2_base_url', models.URLField(blank=True, verbose_name='API 2 — Base URL')),
                ('api_2_enabled', models.BooleanField(default=False, verbose_name='API 2 — Enabled')),
                ('api_3_name', models.CharField(blank=True, max_length=100, verbose_name='API 3 — Name')),
                ('api_3_key', models.CharField(blank=True, max_length=500, verbose_name='API 3 — Key / Token')),
                ('api_3_base_url', models.URLField(blank=True, verbose_name='API 3 — Base URL')),
                ('api_3_enabled', models.BooleanField(default=False, verbose_name='API 3 — Enabled')),
                ('app_env', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=20, verbose_name='App Environment')),
                ('debug_mode', models.BooleanField(default=True, help_text='⚠ Never enable in production', verbose_name='Debug Mode')),
                ('allowed_hosts', models.TextField(blank=True, default='localhost,127.0.0.1', help_text='Comma-separated list of allowed hostnames', verbose_name='Allowed Hosts')),
                ('cors_origins', models.TextField(blank=True, default='http://localhost:5173', help_text='Comma-separated list of allowed frontend origins', verbose_name='CORS Allowed Origins')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'System Setting',
                'db_table': 'system_settings',
            },
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='session_timeout',
            field=models.PositiveIntegerField(default=480, help_text='Minutes'),
        ),
    ]
