# Generated by Django 5.0.6 on 2026-03-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_systemsetting_alter_sitesetting_session_timeout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetting',
            name='api_1_base_url',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='api_1_enabled',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='api_1_key',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='api_1_name',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='api_2_base_url',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='api_2_enabled',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='api_2_key',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='api_2_name',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='api_3_base_url',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='api_3_enabled',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='api_3_key',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='api_3_name',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='eralis_api_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='eRALIS — API Key'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='eralis_base_url',
            field=models.URLField(blank=True, verbose_name='eRALIS — Base URL'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='eralis_enabled',
            field=models.BooleanField(default=False, verbose_name='eRALIS — Enabled'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='eralis_name',
            field=models.CharField(blank=True, default='eRALIS', help_text='Electronic Renewal of Agencies Licence Information System', max_length=100, verbose_name='eRALIS — Name'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='firms_api_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='FIRMS — API Key'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='firms_base_url',
            field=models.URLField(blank=True, verbose_name='FIRMS — Base URL'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='firms_enabled',
            field=models.BooleanField(default=False, verbose_name='FIRMS — Enabled'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='firms_name',
            field=models.CharField(blank=True, default='FIRMS', help_text='Financial Information & Reporting Management System', max_length=100, verbose_name='FIRMS — Name'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='iis_api_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='IIS — API Key'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='iis_base_url',
            field=models.URLField(blank=True, verbose_name='IIS — Base URL'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='iis_enabled',
            field=models.BooleanField(default=False, verbose_name='IIS — Enabled'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='iis_name',
            field=models.CharField(blank=True, default='IIS', help_text='Integrated Information System', max_length=100, verbose_name='IIS — Name'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='mas_api_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='MAS — API Key'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='mas_base_url',
            field=models.URLField(blank=True, verbose_name='MAS — Base URL'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='mas_enabled',
            field=models.BooleanField(default=False, verbose_name='MAS — Enabled'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='mas_name',
            field=models.CharField(blank=True, default='MAS', help_text='Meteorological and Hydrological Services', max_length=100, verbose_name='MAS — Name'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ofs_api_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='OFS — API Key'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ofs_base_url',
            field=models.URLField(blank=True, verbose_name='OFS — Base URL'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ofs_enabled',
            field=models.BooleanField(default=False, verbose_name='OFS — Enabled'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ofs_name',
            field=models.CharField(blank=True, default='OFS', help_text='Online Filing System', max_length=100, verbose_name='OFS — Name'),
        ),
    ]
