# Generated by Django 5.0.6 on 2026-03-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_remove_systemsetting_api_1_base_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='session_timeout',
            field=models.PositiveIntegerField(default=480, help_text='Session timeout in minutes'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='allowed_hosts',
            field=models.TextField(blank=True, default='localhost,127.0.0.1', help_text='Comma-separated hostnames'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='app_env',
            field=models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='cors_origins',
            field=models.TextField(blank=True, default='http://localhost:5173', help_text='Comma-separated frontend origins'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='debug_mode',
            field=models.BooleanField(default=True, help_text='Never enable in production'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='default_from_email',
            field=models.EmailField(blank=True, default='noreply@doe.gov.bt', max_length=254),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='email_backend',
            field=models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text='Use console backend for dev/testing', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='email_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Leave blank to keep existing value.', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='email_timeout',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='email_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='eralis_api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='eralis_base_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='eralis_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='eralis_name',
            field=models.CharField(blank=True, default='eRALIS', help_text='Electronic Renewal of Agencies Licence Information System', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='firms_api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='firms_base_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='firms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='firms_name',
            field=models.CharField(blank=True, default='FIRMS', help_text='Financial Information & Reporting Management System', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='iis_api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='iis_base_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='iis_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='iis_name',
            field=models.CharField(blank=True, default='IIS', help_text='Integrated Information System', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='mas_api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='mas_base_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='mas_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='mas_name',
            field=models.CharField(blank=True, default='MAS', help_text='Meteorological and Hydrological Services', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_auth_url',
            field=models.URLField(blank=True, default='https://staging.bhutanndi.com/authentication/v1/authenticate'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_client_secret',
            field=models.CharField(blank=True, help_text='Leave blank to keep existing value.', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_environment',
            field=models.CharField(choices=[('staging', 'Staging / Dev'), ('production', 'Production')], default='staging', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_schema_id',
            field=models.URLField(blank=True, default='https://dev-schema.ngotag.com/schemas/c7952a0a-e9b5-4a4b-a714-1e5d0a1ae076', help_text='Foundational ID schema URL from NDI team'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_verifier_url',
            field=models.URLField(blank=True, default='https://demo-client.bhutanndi.com/verifier/v1/proof-request'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_webhook_base_url',
            field=models.URLField(blank=True, default='https://your-ngrok-url.ngrok-free.dev', help_text='Public URL reachable by NDI. Re-run register_ndi_webhook after changing.'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_webhook_id',
            field=models.CharField(blank=True, default='eis-bhutan-26', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_webhook_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ofs_api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ofs_base_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ofs_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ofs_name',
            field=models.CharField(blank=True, default='OFS', help_text='Online Filing System', max_length=100),
        ),
    ]
