# Generated by Django 5.0.6 on 2026-03-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_sitesetting_session_timeout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='ndi_issuer_url',
            field=models.URLField(blank=True, default='https://demo-client.bhutanndi.com/issuer/v1', help_text='POST — issue/revoke verifiable credentials. Swagger: https://demo-client.bhutanndi.com/issuer/swagger', verbose_name='NDI Issuer URL (Staging)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ndi_nats_seed',
            field=models.CharField(blank=True, help_text='Dev seed (not secret in staging): SUAPXY7TJFUFE3IX3OEMSLE3JFZJ3FZZRSRSOGSG2ANDIFN77O2MIBHWUM — treat production seed as secret', max_length=500, verbose_name='NDI NATS Seed (Dev)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ndi_nats_url',
            field=models.URLField(blank=True, default='https://natsdemoclient.bhutanndi.com', help_text='NATS server for subscribing to NDI events. Pattern: threadId', verbose_name='NDI NATS URL (Staging)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ndi_nats_ws_url',
            field=models.URLField(blank=True, default='wss://natsdemoclient.bhutanndi.com', verbose_name='NDI NATS WebSocket URL (Staging)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ndi_webhook_register_url',
            field=models.URLField(blank=True, default='https://demo-client.bhutanndi.com/webhook/v1', help_text='Base URL for webhook register/subscribe/unsubscribe. Swagger: https://demo-client.bhutanndi.com/webhook/swagger/', verbose_name='NDI Webhook Service Base URL (Staging)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_auth_url',
            field=models.URLField(blank=True, default='https://staging.bhutanndi.com/authentication/v1/authenticate', help_text='POST — get OAuth2 Bearer token using client_id + client_secret. Swagger: https://staging.bhutanndi.com/authentication/swagger', verbose_name='NDI Auth URL (Staging)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_client_id',
            field=models.CharField(blank=True, help_text='Shared by Bhutan NDI team', max_length=255, verbose_name='NDI Client ID'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_client_secret',
            field=models.CharField(blank=True, help_text='Shared by Bhutan NDI team', max_length=255, verbose_name='NDI Client Secret'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_environment',
            field=models.CharField(choices=[('staging', 'Staging / Dev'), ('production', 'Production')], default='staging', max_length=20, verbose_name='NDI Environment'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_schema_id',
            field=models.URLField(blank=True, default='https://dev-schema.ngotag.com/schemas/c7952a0a-e9b5-4a4b-a714-1e5d0a1ae076', help_text='Schema URL for requesting ID Number and Full Name from Foundational ID credential', verbose_name='NDI Schema ID — Foundational ID'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_verifier_url',
            field=models.URLField(blank=True, default='https://demo-client.bhutanndi.com/verifier/v1/proof-request', help_text='POST — create proof request. GET — poll proof status. Swagger: https://demo-client.bhutanndi.com/verifier/swagger', verbose_name='NDI Verifier URL (Staging)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_webhook_base_url',
            field=models.URLField(blank=True, default='https://your-ngrok-url.ngrok-free.dev', help_text='Public URL this server is reachable at. Use ngrok in dev. Re-run register_ndi_webhook after changing.', verbose_name='Webhook Base URL'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_webhook_id',
            field=models.CharField(blank=True, default='eis-bhutan-26', help_text='Unique ID registered with NDI webhook service', max_length=100, verbose_name='NDI Webhook ID'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_webhook_secret',
            field=models.CharField(blank=True, help_text='OAuth2 v2 fixed token — NDI sends this in Authorization header to authenticate webhook calls to our server', max_length=255, verbose_name='NDI Webhook Secret'),
        ),
    ]
