# Generated by Django 5.0.6 on 2026-03-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_systemsetting_ndi_issuer_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_nats_url',
            field=models.CharField(blank=True, default='https://natsdemoclient.bhutanndi.com', help_text='NATS server URL. Pattern: threadId', max_length=500, verbose_name='NDI NATS URL (Staging)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='ndi_nats_ws_url',
            field=models.CharField(blank=True, default='wss://natsdemoclient.bhutanndi.com', help_text='WebSocket URL — wss:// protocol not validated as URL', max_length=500, verbose_name='NDI NATS WebSocket URL'),
        ),
    ]
