# Generated by Django 5.0.6 on 2026-04-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generationplant',
            old_name='operator',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='generationplant',
            name='commissioned_year',
        ),
        migrations.RemoveField(
            model_name='generationplant',
            name='installed_capacity_kw',
        ),
        migrations.AddField(
            model_name='generationplant',
            name='actual_cost_btn',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Actual Cost (Million Nu.)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='actual_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Actual Cost (Million USD/MW)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='commissioned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='construction_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='design_energy_mu',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Design Energy / Existing Generation (MU)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='dpr_cost',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='DPR Cost (Million Nu.)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='emission_reductions',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='tCO2e per annum', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='firm_power_mw',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Firm Power (MW)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='generator_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='grid_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='idc_cost',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='IDC (Million Nu.)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='installed_capacity_mw',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Installed Capacity (MW)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='ppa_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='scheduled_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='unit_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substation',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='substation',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='substation',
            name='substation_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='bay_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='incoming_feeders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='max_capacity_mw',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Capacity in MW at 0.9 PF rate', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='outgoing_feeders',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
