# Generated by Django 5.0.6 on 2026-05-21 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_rename_operator_generationplant_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletype',
            name='vehicle_category',
        ),
        migrations.DeleteModel(
            name='VehicleCategory',
        ),
    ]
