# Generated by Django 5.0.6 on 2026-05-21 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_remove_vehicletype_vehicle_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['parent__vehicle_type_name', 'vehicle_type_name']},
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='master_data.vehicletype'),
        ),
    ]
