# Generated by Django 5.0.6 on 2026-05-26 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_add_vehicletype_parent_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solarenergysize',
            options={'ordering': ['category']},
        ),
        migrations.RenameField(
            model_name='solarenergysize',
            old_name='energy_kwh',
            new_name='energy_generation_kwh',
        ),
        migrations.RenameField(
            model_name='solarenergysize',
            old_name='capacity_kwp',
            new_name='installed_capacity_kwp',
        ),
        migrations.RemoveField(
            model_name='solarenergysize',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='solarenergysize',
            name='panel_type',
        ),
        migrations.RemoveField(
            model_name='solarenergysize',
            name='size_category',
        ),
        migrations.AddField(
            model_name='solarenergysize',
            name='category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solarenergysize',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solar_sizes', to='master_data.sector'),
        ),
    ]
