# Generated by Django 5.0.6 on 2026-06-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_alter_solarenergysize_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generationplant',
            options={'ordering': ['plant_type', 'plant_name']},
        ),
        migrations.RenameField(
            model_name='generationplant',
            old_name='unit_count',
            new_name='no_of_units',
        ),
        migrations.RenameField(
            model_name='generationplant',
            old_name='ppa_signed_date',
            new_name='ppa_signed',
        ),
        migrations.RenameField(
            model_name='generationplant',
            old_name='commissioned_date',
            new_name='year_of_operation',
        ),
        migrations.RemoveField(
            model_name='generationplant',
            name='design_energy_mu',
        ),
        migrations.RemoveField(
            model_name='generationplant',
            name='emission_reductions',
        ),
        migrations.RemoveField(
            model_name='generationplant',
            name='firm_power_mw',
        ),
        migrations.RemoveField(
            model_name='generationplant',
            name='idc_cost',
        ),
        migrations.RemoveField(
            model_name='generationplant',
            name='installed_capacity_mw',
        ),
        migrations.RemoveField(
            model_name='generationplant',
            name='source_type',
        ),
        migrations.AddField(
            model_name='generationplant',
            name='acronym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='delay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='emission_reductions_pa',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='energy',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='existing_energy_generation',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='firm_power',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='gewog',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='idc',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='installed_capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='plant_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='plant_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='set_numbers',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='storage_size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='system_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generationplant',
            name='village',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='generationplant',
            name='actual_cost_btn',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='generationplant',
            name='actual_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='generationplant',
            name='construction_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generationplant',
            name='dpr_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='generationplant',
            name='generator_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generationplant',
            name='grid_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generationplant',
            name='owner',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='generationplant',
            name='plant_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='generationplant',
            name='plant_name',
            field=models.CharField(max_length=250),
        ),
    ]
