# Generated by Django 5.0.6 on 2026-06-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_alter_generationplant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substation',
            name='dzo_iso_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='substation',
            name='dzongkhag_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='substation',
            name='gewog_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='substation',
            name='plant_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='substation',
            name='plant_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substation',
            name='plant_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='substation',
            name='plant_type_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substation',
            name='region_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='substation',
            name='substation_type_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
