# Generated by Django 5.0.6 on 2026-06-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_substation_dzo_iso_code_substation_dzongkhag_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substationtransformer',
            name='acronym',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='dzo_iso_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='dzongkhag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='dzongkhag_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='gewog',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='gewog_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='no_of_transformers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='plant_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='plant_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='plant_type_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='region_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='status_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='substation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='substation_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='substation_type_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substationtransformer',
            name='transformer_capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
