# Generated by Django 5.0.6 on 2026-06-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_substationtransformer_acronym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substationtransformer',
            name='transformer_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
