# Generated by Django 5.0.6 on 2026-06-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_alter_substationtransformer_transformer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationplant',
            name='plant_subtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
