# Generated by Django 5.0.6 on 2026-06-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_generationplant_plant_subtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dzongkhag',
            options={'ordering': ['dzongkhag']},
        ),
        migrations.RenameField(
            model_name='dzongkhag',
            old_name='dzongkhag_name',
            new_name='dzongkhag',
        ),
        migrations.AddField(
            model_name='dzongkhag',
            name='iso_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dzongkhag',
            name='region_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dzongkhag',
            name='region',
            field=models.CharField(choices=[('Eastern region', 'Eastern region'), ('Western region', 'Western region'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
    ]
