# Generated by Django 5.0.6 on 2026-04-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitygeneration',
            name='domestic_sales_amount',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Nu. Millions', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='domestic_sales_generation',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='export_amount',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Nu. Millions', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='export_generation',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='export_tariff',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Nu. per unit or negotiated rate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='internal_consumption',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='target_generation',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='industrypowerdata',
            name='app_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='industrypowerdata',
            name='cod',
            field=models.CharField(blank=True, help_text='Commercial Operation Date', max_length=100),
        ),
        migrations.AddField(
            model_name='industrypowerdata',
            name='feeder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='industrypowerdata',
            name='feeding_substation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='industrypowerdata',
            name='validity_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='industrypowerdata',
            name='voltage_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='export_mu',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Export in MU', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='supplydemandforecastingdata',
            name='export_gwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='supplydemandforecastingdata',
            name='firm_power',
            field=models.IntegerField(blank=True, help_text='MW', null=True),
        ),
        migrations.AddField(
            model_name='supplydemandforecastingdata',
            name='import_gwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='supplydemandforecastingdata',
            name='installed_capacity_mw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='trademarketdata',
            name='iex_margin_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trademarketdata',
            name='igst_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trademarketdata',
            name='nldc_app_fee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trademarketdata',
            name='nldc_op_charge',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trademarketdata',
            name='successful_portfolios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trademarketdata',
            name='trader_margin_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
