# Generated by Django 5.0.6 on 2026-04-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0002_electricitygeneration_domestic_sales_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='aux_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auxiliary rate %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='domestic_tariff',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='export_tariff',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='export_tariff_iex',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='NHP only', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='export_tariff_ptc',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='NHP only', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='generation_gwh',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='line_losses_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Line losses %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='wheeling_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Nu./kWh', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='electricityroyaltydata',
            name='royalty_rate_percent',
            field=models.DecimalField(decimal_places=2, help_text='Legacy: gen_royalty_rate', max_digits=5),
        ),
    ]
