# Generated by Django 5.0.6 on 2026-04-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0003_electricityroyaltydata_aux_rate_and_more'),
        ('master_data', '0002_rename_operator_generationplant_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrypowerdata',
            name='feeding_substation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.substation'),
        ),
        migrations.AlterField(
            model_name='industrypowerdata',
            name='voltage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.electricitytype'),
        ),
        migrations.AlterField(
            model_name='transmissionlinedata',
            name='line_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines_out', to='master_data.substation'),
        ),
        migrations.AlterField(
            model_name='transmissionlinedata',
            name='line_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines_in', to='master_data.substation'),
        ),
    ]
