# Generated by Django 5.0.6 on 2026-04-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0004_alter_industrypowerdata_feeding_substation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasgenerationdata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionlinedata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributiontransformerdata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricityconsumerdata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricityconsumption',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricityimportexport',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportreadata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlygenerationdata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrologydata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industrypowerdata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substationloaddata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplydemandforecastingdata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trademarketdata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
