# Generated by Django 5.0.6 on 2026-05-01 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0005_biogasgenerationdata_day_distributionlinedata_day_and_more'),
        ('master_data', '0002_rename_operator_generationplant_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biogasgenerationdata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='biogasgenerationdata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='distributionlinedata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='distributionlinedata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='distributiontransformerdata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='distributiontransformerdata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='electricityconsumerdata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='electricityconsumerdata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='electricityconsumption',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='electricityconsumption',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='electricitygeneration',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='electricitygeneration',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='electricityimportexport',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='electricityimportexport',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='electricityroyaltydata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='electricityroyaltydata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='electricitysalesdata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='electricitysalesdata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='exportreadata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='exportreadata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='hourlygenerationdata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='hourlygenerationdata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='hydrologydata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='hydrologydata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='industrypowerdata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='industrypowerdata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='plantdailygeneration',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='plantdailygeneration',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='substationloaddata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='substationloaddata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='supplydemandforecastingdata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='supplydemandforecastingdata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='trademarketdata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='trademarketdata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
        migrations.AlterField(
            model_name='transmissionlinedata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource'),
        ),
        migrations.AlterField(
            model_name='transmissionlinedata',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear'),
        ),
    ]
