# Generated by Django 5.0.6 on 2026-05-06 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0006_alter_biogasgenerationdata_data_source_and_more'),
        ('master_data', '0002_rename_operator_generationplant_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HydrologyData',
            new_name='HydropowerData',
        ),
        migrations.AlterModelTable(
            name='HydropowerData',
            table='electricity_hydropower',
        ),
    ]
