# Generated by Django 5.0.6 on 2026-05-21 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0007_hydropowerdata_delete_hydrologydata'),
        ('master_data', '0004_add_vehicletype_parent_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydropowerdata',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydropower_records', to='master_data.generationplant'),
        ),
    ]
