# Generated by Django 5.0.6 on 2026-06-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0009_hydrologydata_delete_hydropowerdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricitygeneration',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='hourlygenerationdata',
            options={'ordering': ['-date', '-hour']},
        ),
        migrations.AlterModelOptions(
            name='plantdailygeneration',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='electricitygeneration',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hourlygenerationdata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='plantdailygeneration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='export_chp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='export_dhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='export_khp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='export_mhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='export_nhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='export_thp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='generation_bhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='generation_chp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='generation_dhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='generation_khp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='generation_mhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='generation_nhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='generation_thp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='hourlygenerationdata',
            name='export_chp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='hourlygenerationdata',
            name='export_dhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='hourlygenerationdata',
            name='export_khp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='hourlygenerationdata',
            name='export_mhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='hourlygenerationdata',
            name='export_nhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='hourlygenerationdata',
            name='export_thp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='hourlygenerationdata',
            name='generation_bhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='hourlygenerationdata',
            name='generation_chp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='hourlygenerationdata',
            name='generation_dhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='hourlygenerationdata',
            name='generation_khp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='hourlygenerationdata',
            name='generation_mhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='hourlygenerationdata',
            name='generation_nhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='hourlygenerationdata',
            name='generation_thp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='export_chp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='export_dhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='export_khp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='export_mhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='export_nhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='export_thp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='generation_bhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='generation_chp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='generation_dhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='generation_khp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='generation_mhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='generation_nhp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plantdailygeneration',
            name='generation_thp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='data_sources',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='domestic_sales_amount',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='domestic_sales_generation',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='export_amount',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='export_generation',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='export_tariff',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='generation_gwh',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='internal_consumption',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='target_generation',
        ),
        migrations.RemoveField(
            model_name='hourlygenerationdata',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='hourlygenerationdata',
            name='unit1_mw',
        ),
        migrations.RemoveField(
            model_name='hourlygenerationdata',
            name='unit2_mw',
        ),
        migrations.RemoveField(
            model_name='hourlygenerationdata',
            name='unit3_mw',
        ),
        migrations.RemoveField(
            model_name='hourlygenerationdata',
            name='unit4_mw',
        ),
        migrations.RemoveField(
            model_name='hourlygenerationdata',
            name='unit5_mw',
        ),
        migrations.RemoveField(
            model_name='hourlygenerationdata',
            name='unit6_mw',
        ),
        migrations.RemoveField(
            model_name='plantdailygeneration',
            name='export_mu',
        ),
        migrations.RemoveField(
            model_name='plantdailygeneration',
            name='generation_mu',
        ),
        migrations.RemoveField(
            model_name='plantdailygeneration',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='plantdailygeneration',
            name='target_mu',
        ),
    ]
