# Generated by Django 5.0.6 on 2026-06-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0010_alter_electricitygeneration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricitygeneration',
            options={'ordering': ['-date', 'acronym']},
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='export_chp',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='export_dhp',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='export_khp',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='export_mhp',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='export_nhp',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='export_thp',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='generation_bhp',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='generation_chp',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='generation_dhp',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='generation_khp',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='generation_mhp',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='generation_nhp',
        ),
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='generation_thp',
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='acronym',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='domestic_sales_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='domestic_sales_generation',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='export_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='export_generation',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='export_tariff',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='generation',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='ingest_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='internal_consumption',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='electricitygeneration',
            name='target_generation',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
