# Generated by Django 5.0.6 on 2026-06-07 13:22

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0012_alter_electricitygeneration_domestic_sales_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlantDailyGeneration',
            new_name='PlantGenerationDaily',
        ),
        migrations.AddField(
            model_name='plantgenerationdaily',
            name='load_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantgenerationdaily',
            name='ingest_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantgenerationdaily',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
