# Generated by Django 5.0.6 on 2026-06-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0013_plantgenerationdaily_delete_plantdailygeneration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantgenerationdaily',
            name='ingest_version',
        ),
        migrations.RemoveField(
            model_name='plantgenerationdaily',
            name='load_date',
        ),
    ]
