# Generated by Django 5.0.6 on 2026-06-07 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0016_hourlygenerationdata_unit_fields_v2'),
        ('master_data', '0009_alter_substationtransformer_transformer_code'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hourlygenerationdata',
            new_name='electricity_plant_i_aee8d7_idx',
            old_name='elec_hourly_plant_date_hour_idx',
        ),
        migrations.RemoveField(
            model_name='transmissionlinedata',
            name='length_km',
        ),
        migrations.RemoveField(
            model_name='transmissionlinedata',
            name='line_name',
        ),
        migrations.RemoveField(
            model_name='transmissionlinedata',
            name='voltage_kv',
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='ampacity_75',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='ampacity_85',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='circuit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='configuration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='line_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='line_length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='mw_75',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='mw_85',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='sil',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='tower_a',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='tower_b',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='tower_c',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='tower_d',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='tower_q',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='tower_spl',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transmissionlinedata',
            name='voltage_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hourlygenerationdata',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hourly_records', to='master_data.generationplant'),
        ),
        migrations.AlterField(
            model_name='transmissionlinedata',
            name='conductor_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transmissionlinedata',
            name='line_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines_out', to='master_data.substation'),
        ),
        migrations.AlterField(
            model_name='transmissionlinedata',
            name='line_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines_in', to='master_data.substation'),
        ),
    ]
