# Generated by Django 5.0.6 on 2026-06-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0017_rename_elec_hourly_plant_date_hour_idx_electricity_plant_i_aee8d7_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributionlinedata',
            old_name='kv11_km',
            new_name='kv11',
        ),
        migrations.RenameField(
            model_name='distributionlinedata',
            old_name='kv33_km',
            new_name='kv33',
        ),
        migrations.RenameField(
            model_name='distributionlinedata',
            old_name='kv6_6_km',
            new_name='kv6_6',
        ),
        migrations.RenameField(
            model_name='distributionlinedata',
            old_name='lv_line_km',
            new_name='lv_line',
        ),
        migrations.AddField(
            model_name='distributionlinedata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
