# Generated by Django 5.0.6 on 2026-06-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0018_rename_kv11_km_distributionlinedata_kv11_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributiontransformerdata',
            name='capacity_kva',
        ),
        migrations.RemoveField(
            model_name='distributiontransformerdata',
            name='count',
        ),
        migrations.AddField(
            model_name='distributiontransformerdata',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='distributiontransformerdata',
            name='capacity_bpc',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='distributiontransformerdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributiontransformerdata',
            name='no_of_transformers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='distributiontransformerdata',
            name='no_of_transformers_bpc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='distributiontransformerdata',
            name='voltage_ratio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='distributiontransformerdata',
            name='transformer_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
