# Generated by Django 5.0.6 on 2026-06-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0019_remove_distributiontransformerdata_capacity_kva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricitysalesdata',
            name='bpc_category',
        ),
        migrations.RemoveField(
            model_name='electricitysalesdata',
            name='sales_mu',
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='agriculture',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='commercial',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='cottage_small_industries',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='electric_vehicles',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='highlands',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='hv_industries',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='industries',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='institutions',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='lv_bulk',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='mv_industries',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='power_house_auxiliaries',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='religious_institutions',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='rural_community_lhakhangs',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='rural_cooperatives',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='rural_microtrades',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='rural_residents',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='street_lighting',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='temporary_connections',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricitysalesdata',
            name='urban_residents',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='electricitysalesdata',
            name='dzongkhag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
