# Generated by Django 5.0.6 on 2026-06-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0020_sales_data_rework_flat_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricityconsumerdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
