# Generated by Django 5.0.6 on 2026-06-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0022_consumer_rework_flat_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrologydata',
            name='inflow_cumecs',
        ),
        migrations.AddField(
            model_name='hydrologydata',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hydrologydata',
            name='inflow',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hydrologydata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
