# Generated by Django 5.0.6 on 2026-06-08 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0023_remove_hydrologydata_inflow_cumecs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricitygeneration',
            name='ingest_version',
        ),
    ]
