# Generated by Django 5.0.6 on 2026-06-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0024_remove_electricitygeneration_ingest_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hydrologydata',
            options={'ordering': ['-date', 'acronym']},
        ),
        migrations.AlterUniqueTogether(
            name='hydrologydata',
            unique_together={('acronym', 'date')},
        ),
        migrations.RemoveField(
            model_name='hydrologydata',
            name='plant',
        ),
    ]
