# Generated by Django 5.0.6 on 2026-06-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0025_alter_hydrologydata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportreadata',
            name='energy_mu',
        ),
        migrations.RemoveField(
            model_name='exportreadata',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='exportreadata',
            name='tariff_nu',
        ),
        migrations.AddField(
            model_name='exportreadata',
            name='chp_energy',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exportreadata',
            name='chp_tariff',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exportreadata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportreadata',
            name='dhp_energy',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exportreadata',
            name='dhp_tariff',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exportreadata',
            name='khp_energy',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exportreadata',
            name='khp_tariff',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exportreadata',
            name='mhp_energy',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exportreadata',
            name='mhp_tariff',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exportreadata',
            name='nhp_energy',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exportreadata',
            name='nhp_tariff',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exportreadata',
            name='thp_energy',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exportreadata',
            name='thp_tariff',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
