# Generated by Django 5.0.6 on 2026-06-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0026_remove_exportreadata_energy_mu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricityroyaltydata',
            name='generation_gwh',
        ),
        migrations.RemoveField(
            model_name='electricityroyaltydata',
            name='net_export_energy_mu',
        ),
        migrations.RemoveField(
            model_name='electricityroyaltydata',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='electricityroyaltydata',
            name='royalty_energy_mu',
        ),
        migrations.RemoveField(
            model_name='electricityroyaltydata',
            name='royalty_rate_percent',
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='gen_royalty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='generation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='net_export_energy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='electricityroyaltydata',
            name='aux_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='electricityroyaltydata',
            name='export_tariff_iex',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='electricityroyaltydata',
            name='export_tariff_ptc',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='electricityroyaltydata',
            name='line_losses_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='electricityroyaltydata',
            name='wheeling_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
