# Generated by Django 5.0.6 on 2026-06-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0027_remove_electricityroyaltydata_generation_gwh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricityroyaltydata',
            name='net_export_energy',
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='rebate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='schedule_export',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='schedule_export_iex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='electricityroyaltydata',
            name='schedule_export_ptc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
