# Generated by Django 5.0.6 on 2026-06-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0029_trademarketexport_trademarketimport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademarketimport',
            name='block',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trademarketimport',
            name='ctu_charge_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trademarketimport',
            name='iex_margin_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trademarketimport',
            name='igst_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trademarketimport',
            name='india_trans_loss',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trademarketimport',
            name='nldc_app_fee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trademarketimport',
            name='nldc_op_charge',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trademarketimport',
            name='qty_mw',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trademarketimport',
            name='rate_per_mwh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trademarketimport',
            name='successful_portfolios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trademarketimport',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trademarketimport',
            name='trader_margin_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
