# Generated by Django 5.0.6 on 2026-06-08 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0030_trademarketimport_block_and_more'),
        ('master_data', '0009_alter_substationtransformer_transformer_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeMarketImportDam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('toe_calculated', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=40, null=True)),
                ('qty_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rate_per_mwh', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('india_trans_loss', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('ctu_charge_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('iex_margin_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('igst_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('trader_margin_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('nldc_app_fee', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('successful_portfolios', models.IntegerField(blank=True, null=True)),
                ('nldc_op_charge', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear')),
            ],
            options={
                'db_table': 'electricity_trade_market_import_dam',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='TradeMarketImport',
        ),
    ]
