# Generated by Django 5.0.6 on 2026-06-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0032_trademarketimportrtm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biogasgenerationdata',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='biogasgenerationdata',
            name='capacity_m3',
        ),
        migrations.RemoveField(
            model_name='biogasgenerationdata',
            name='plant_count',
        ),
        migrations.AddField(
            model_name='biogasgenerationdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biogasgenerationdata',
            name='fiscal_year',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='biogasgenerationdata',
            name='medium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biogasgenerationdata',
            name='plant_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biogasgenerationdata',
            name='small_10m3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biogasgenerationdata',
            name='small_4m3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biogasgenerationdata',
            name='small_6m3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biogasgenerationdata',
            name='small_8m3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biogasgenerationdata',
            name='unspecified',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biogasgenerationdata',
            name='dzongkhag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
