# Generated by Django 5.0.6 on 2026-06-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0033_alter_biogasgenerationdata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrypowerdata',
            name='industry_name',
        ),
        migrations.RemoveField(
            model_name='industrypowerdata',
            name='max_power_mw',
        ),
        migrations.AddField(
            model_name='industrypowerdata',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypowerdata',
            name='industry_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrypowerdata',
            name='max_power',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='industrypowerdata',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industrypowerdata',
            name='app_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industrypowerdata',
            name='cod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industrypowerdata',
            name='dzongkhag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industrypowerdata',
            name='feeder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industrypowerdata',
            name='feeding_substation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industrypowerdata',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industrypowerdata',
            name='validity_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industrypowerdata',
            name='voltage_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
