# Generated by Django 5.0.6 on 2026-06-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0035_alter_substationloaddata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplydemandforecastingdata',
            options={'ordering': ['-year']},
        ),
        migrations.RemoveField(
            model_name='supplydemandforecastingdata',
            name='forecast_year',
        ),
        migrations.RemoveField(
            model_name='supplydemandforecastingdata',
            name='peak_load_mw',
        ),
        migrations.AddField(
            model_name='supplydemandforecastingdata',
            name='peakload_mw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplydemandforecastingdata',
            name='export_gwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplydemandforecastingdata',
            name='firm_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplydemandforecastingdata',
            name='generation_gwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplydemandforecastingdata',
            name='import_gwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplydemandforecastingdata',
            name='installed_capacity_mw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplydemandforecastingdata',
            name='load_gwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='supplydemandforecastingdata',
            name='year',
        ),
        migrations.AddField(
            model_name='supplydemandforecastingdata',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
