# Generated by Django 5.0.6 on 2026-06-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0036_alter_supplydemandforecastingdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmissionlinedata',
            name='line_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transmissionlinedata',
            name='line_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
