# Generated by Django 5.0.6 on 2026-06-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0037_alter_transmissionlinedata_line_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmissionlinedata',
            name='voltage_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
