# Generated by Django 5.0.6 on 2026-04-05 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_type', models.CharField(max_length=100)),
                ('co2_factor', models.DecimalField(decimal_places=8, max_digits=18)),
                ('ch4_factor', models.DecimalField(decimal_places=8, max_digits=18)),
                ('n2o_factor', models.DecimalField(decimal_places=8, max_digits=18)),
                ('unit', models.CharField(max_length=50)),
                ('source', models.CharField(default='IPCC_DEFAULT', max_length=100)),
                ('applicability', models.CharField(blank=True, max_length=200)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ghg_emission_factor',
            },
        ),
        migrations.CreateModel(
            name='GHGCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('activity_data', models.DecimalField(decimal_places=6, max_digits=18)),
                ('co2_emissions', models.DecimalField(decimal_places=6, max_digits=18)),
                ('ch4_emissions', models.DecimalField(decimal_places=6, max_digits=18)),
                ('n2o_emissions', models.DecimalField(decimal_places=6, max_digits=18)),
                ('co2_equivalent', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('emission_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ghg.emissionfactor')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ghg_calculation',
            },
        ),
    ]
