# Generated by Django 5.0.6 on 2026-06-05 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0005_alter_solarenergysize_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('toe_calculated', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('airlines', models.CharField(help_text='Name of the Airline (e.g. Drukair, Bhutan Airlines)', max_length=150)),
                ('aircraft_type', models.CharField(help_text='Aircraft Type (e.g. Airbus A319, ATR 42)', max_length=100)),
                ('no_of_flights_operating_per_day', models.PositiveIntegerField(blank=True, help_text='Number of flights operating per day', null=True)),
                ('domestic_fuel_consumption', models.DecimalField(blank=True, decimal_places=4, help_text='Domestic fuel consumption in kilolitres (KL) or equivalent', max_digits=18, null=True)),
                ('international_fuel_consumption', models.DecimalField(blank=True, decimal_places=4, help_text='International fuel consumption in kilolitres (KL) or equivalent', max_digits=18, null=True)),
                ('domestic_landings', models.PositiveIntegerField(blank=True, help_text='Number of domestic landings', null=True)),
                ('international_landings', models.PositiveIntegerField(blank=True, help_text='Number of international landings', null=True)),
                ('domestic_takeoffs', models.PositiveIntegerField(blank=True, help_text='Number of domestic take-offs', null=True)),
                ('international_takeoffs', models.PositiveIntegerField(blank=True, help_text='Number of international take-offs', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datasource')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='master_data.datacollectionyear')),
            ],
            options={
                'verbose_name': 'Air Transport Record',
                'verbose_name_plural': 'Air Transport Records',
                'db_table': 'air_transport',
                'ordering': ['-year', 'airlines'],
            },
        ),
    ]
