# Generated by Django 5.0.6 on 2026-06-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_transport', '0002_aircraftactivity_aviationfuelconsumption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraftactivity',
            options={'ordering': ['-date', 'airlines'], 'verbose_name': 'Aircraft Activity Record', 'verbose_name_plural': 'Aircraft Activity Records'},
        ),
        migrations.AlterModelOptions(
            name='aviationfuelconsumption',
            options={'ordering': ['-date', 'airlines'], 'verbose_name': 'Aviation Fuel Consumption Record', 'verbose_name_plural': 'Aviation Fuel Consumption Records'},
        ),
        migrations.AddField(
            model_name='aircraftactivity',
            name='date',
            field=models.DateField(blank=True, db_column='date', null=True),
        ),
        migrations.AddField(
            model_name='aviationfuelconsumption',
            name='date',
            field=models.DateField(blank=True, db_column='date', null=True),
        ),
    ]
